branches:
  only:
  - master
  - develop
  - /^greenkeeper-.*$/
language: node_js
node_js:
  - "7.5.0"
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && npm run deploy-storybook

env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8