branches:
  only:
  - master
  - develop
  - /^greenkeeper-.*$/
language: node_js
node_js:
  - "7.5.0"
cache:
  directories:
    - node_modules
install:
  - npm install
after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "develop" && npm run deploy-storybook